services:
    wordpress:
        image: wordpress
        ports:
            - "8089:80"
        depends_on:
            - mysql
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: "pindakaas"
            WORDPRESS_DB_NAME: db_wordpress
        networks:
            mininet:
                ipv4_address: "10.56.1.21"

    mysql:
        image: "mysql:5.7"
        environment:
            MYSQL_DATABASE: db_wordpress
            MYSQL_ROOT_PASSWORD: "pindakaas"
        volumes:
            - ./volumes/wordpress_mysql:/var/lib/mysql
        networks:
            mininet:
                ipv4_address: "10.56.1.20"

networks:
    mininet:
        ipam:
            driver: default
            config:
                - subnet: "10.56.1.0/24"

